printWidth: 160
tabWidth: 2
trailingComma: all
useTabs: true
semi: true
jsxSingleQuote: false
bracketSpacing: true
bracketSameLine: false
singleQuote: true
arrowParens: always
cursorOffset: -1
embeddedLanguageFormatting: auto
endOfLine: lf
htmlWhitespaceSensitivity: css
insertPragma: false
